### PR TITLE
Fixes and new features

### PR DESCRIPTION
**Pull request by nighthawk**
Seems like my previous work on the completion blocks got broken in the last commits of your repo. I've merged it into my repo and got it working again. I've refactored it a little bit, to make it harder to break it again ;)

I've also added these two things:
• Auto-hiding of the divider bar. It'll only be shown during folding.
• An optional property to restrict panning to a certain CGRect of the FoldView. I am using this to only allow panning from a NavigationBar.

### CODE REVIEW

**Comment by honcheng** [comment]
Thanks again for the good stuff. Nice to see this project getting more contributions!

**Comment by honcheng** [comment]
Do you have problem closing the fold with the restrictedEdgeDraggingRect?

**Comment by nighthawk** [comment]
That is working fine for me so far. In my app, I've set that rect to the navigation bar's frame. What issue do you have?

**Comment by aornano** [comment]
It's not clear how to programmatically unfold left or right controllers (for example both uitables) inside PaperFoldNavigationController, please give more details:

For example (inside LeftViewController just manually dragged):
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
  {
  UITableViewController *viewController = [[UITableViewController alloc] initWithStyle:UITableViewStylePlain];
  [self.navigationController pushViewController:viewController animated:YES];
  PaperFoldNavigationController *nav= (PaperFoldNavigationController *)[UIApplication sharedApplication].keyWindow.rootViewController; (to retrieve my navigation controller)
  [nav.paperFoldView setPaperFoldState:PaperFoldStateDefault];
  NSLog(@"%u",[go.paperFoldView state]);
  
  [tableView deselectRowAtIndexPath:indexPath animated:YES];
  }

It work, Paperfold automatically drag to centerviewcontroller BUT if I come back manually to drag to the left controller this last is blocked (cell are blanks and the not respond to selection) . What's could be the problems?

**Pull request merged**
