### PR TITLE
Create PaperFold.podspec

### LINKED ISSUE #15: CocoaPods integration
Would be cool to have PaperFold available by the cocoaPods

### PR DESCRIPTION
**Pull request by texastoland**
closes #15

### CODE REVIEW

**Comment by honcheng** [comment]
Thanks. Away on a trip at the moment. Will look at this when I'm back.

**Comment by texastoland** [comment]
No worries. I also have modifications for using PaperFoldNavigationController with storyboards and segues if you'd like another pull request later? Or I could gist them for review.

**Comment by honcheng** [comment]
Hi, Looks like you just closed this. Should I merge it?

**Comment by texastoland** [comment]
Oh sorry I noticed I had an issue open and forget it was a PR. Thx :metal:

**Pull request merged**
